neuralet/smart-social-distancing

gstreamer-playground/README.md

* allow external access
* working pipeline (mostly, the mpegtsmux was missing)

add working test pipeline

---

libs/core.py

not sure if this will work immeditely, but we know these components are needed now

change pipeline string to match working test

---

libs/detectors/edgetpu/mobilenet_ssd.py
libs/detectors/edgetpu/pedestrian_ssd_mobilenet_v2.py
libs/detectors/edgetpu/pedestrian_ssdlite_mobilenet_v2.py

this [issue](https://github.com/neuralet/neuralet/issues/128) is fixed

git lfs model paths modified

---

README.md

Updated readme about coral's problem in building the frontend

---

config-jetson.ini
download_jetson_nano_trt.sh
libs/detectors/jetson/detector.py

This model is trained on softbio dataset, working for jetson nano.

Added support for TRT_ssd_mobilenet_v2_pedestrian_softbio

---

README.md
create_reports.py
download-x86-openpifpaf-model.sh
libs/detectors/x86/openpifpaf.py
libs/distancing.py
libs/loggers/loggers.py

Facemask data is added to the csv stats and also to daily and hourly reports.
Also I added some fixes to be able to run this project on Openvino without Facemask classifier

Add facemask data to reports

---

api/areas.py
api/cameras.py
api/config.py
api/processor_api.py
api/queue_manager.py
api/settings.py
api/slack.py
api/utils.py
run_processor_api.py

- The endpoints defined in `api/processor_api.py` were moved into multiple files (cameras, areas and slack).
- The config management was moved into a Singleton. Same with the QueueManager.

Refactor fast api

---

api/areas.py
api/cameras.py
api/config.py
api/processor_api.py
api/reports.py
api/slack.py
api/utils.py
libs/distancing.py
sample_startup.bash

Improving the swagger API documentation

Improve API documentation.

---

README.md
config-x86-gpu.ini
libs/detectors/x86/openpifpaf.py
libs/distancing.py
x86-gpu.Dockerfile

This PR will add a docker file and instruction to run Smart Social Distancing on x86 nodes with GPU.

Gpu support

---

README.md
config-coral.ini
config-x86.ini
create_reports.py
libs/detectors/edgetpu/posenet.py
libs/distancing.py
libs/utils/visualization_utils.py

Adding facemask label in boxes.
Including the minscore threshold for mask detection in the classifier.

Facemask improvements.

---

config-x86-gpu.ini

added tracker parameters to gpu config

---

api/reports.py
api/utils.py

This endpoint allows downloading all raw csv data for all currently configured cameras

Add export_all endpoint

---

libs/distancing.py

Checking classifier model before inferencing.

Fixed mined issues at classifier inference

---

api/routers/cameras.py

- Fixed issue with `GET /cameras/{camera_id}/calibration_image` (It failed if the camera didn't have a default image saved
- Made it so that endpoints that require a default image capture the current frame and save it as default image in cases where te default image doesn't exist

Fix: Camera image endpoints capture default image

---

api/models/metrics.py
api/routers/cameras.py
libs/loggers/source_loggers/video_logger.py
libs/metrics/base.py
libs/metrics/face_mask_usage.py
libs/metrics/occupancy.py
libs/metrics/social_distancing.py

- Include occupancy in the video logger.
- Include the OccupancyThreshold in the metrics

Occupancy improvements

---

README.md
api/models/camera.py
api/routers/cameras.py
config-coral.ini
config-jetson.ini
config-x86-gpu-tensorrt.ini
config-x86-gpu.ini
config-x86-openvino.ini
config-x86.ini
libs/cv_engine.py
libs/engine_threading.py
libs/loggers/source_loggers/file_system_logger.py
libs/loggers/source_loggers/logger.py
libs/loggers/source_loggers/raw_data_logger.py
libs/loggers/source_loggers/s3_logger.py
libs/loggers/source_loggers/video_logger.py
libs/loggers/source_loggers/web_hook_logger.py

Enabling configure the video live feed per source.

Improve video live feed (Enabling configure the video live feed per source).

---

libs/metrics/base.py
libs/metrics/occupancy.py

The occupancy metrics can not be aggregated using "sum". This PR fixes the issue aggregating correctly the metrics for the weekly occupancy.

Fix weekly occupancy metric.

---

README.md
api/models/core.py
api/processor_api.py
api/routers/app.py
api/routers/area_loggers.py
api/routers/areas.py
api/routers/cameras.py
api/routers/classifier.py
api/routers/config.py
api/routers/core.py
api/routers/detector.py
api/routers/metrics/area_metrics.py
api/routers/metrics/camera_metrics.py
api/routers/metrics/metrics.py
api/routers/periodic_tasks.py
api/routers/source_loggers.py
api/routers/source_post_processors.py
api/routers/tracker.py
constants.py
libs/metrics/base.py
libs/metrics/face_mask_usage.py
libs/metrics/occupancy.py
libs/metrics/social_distancing.py

Small fixes in the processor API
- The response of the endpoints in the PUT and POST operation was changed to keep the GET format.
- The metrics endpoints were refactored to avoid repeating code.

Api improvements

---

config-jetson-nano.ini
jetson-nano.Dockerfile

- Fixing jetson-nano config file
- Fixing jetson-nano dockerfile (#116)

Fix in jetson-nano dockerfile.

---

amd64-usbtpu.Dockerfile
coral-dev-board.Dockerfile

The master branch of the project https://github.com/google-coral/project-posenet was updated the last week. The change applied is not compatible with our project.
I changed the dockerfiles for coral and the accelerator to use the previous commit.
Maybe in the future queue can modify our solution to use the master version of posenet.

Fix posenet reference in coral devices.

---

README.md
config-coral.ini
config-jetson-nano.ini
config-jetson-tx2.ini
config-x86-gpu-tensorrt.ini
config-x86-gpu.ini
config-x86-openvino.ini
config-x86.ini

- Updated references from beta.lanthorn to app.lanthorn
- Updated configs to direct to the dashboardURL (as the README suggests)

Updated references from beta.lanthorn to app.lanthorn

---

libs/loggers/source_loggers/video_logger.py
libs/utils/visualization_utils.py

Draw Region of Interest Contour in Live Feed

Draw Region of Interest Contour in Live Feed

---

api/models/camera.py
api/routers/cameras.py
config-coral.ini
config-jetson-nano.ini
config-jetson-tx2.ini
config-x86-gpu-tensorrt.ini
config-x86-gpu.ini
config-x86-openvino.ini
config-x86.ini
libs/metrics/in_out.py
libs/source_post_processors/objects_filtering.py
libs/utils/config.py
libs/utils/utils.py

- List cameras configurations
- Fix to error in getting logs directories
- Fix to default location for config files

List cameras configurations

---

libs/cv_engine.py
sample_startup.bash

Also avoid downloading sample video when not using it

Fix crash when logging without classifier

---

README.md
docker-compose-amd64.yml
docker-compose-coral-dev.yml
docker-compose-gpu-tensorrt.yml
docker-compose-gpu.yml
docker-compose-jetson-nano.yml
docker-compose-jetson-tx2.yml
docker-compose-x86-openvino.yml
docker-compose-x86.yml
docker-compose.yml

- Include docker-compose support for building and running the processor images

Include docker compose

---

api/models/area.py
api/models/occupancy_rule.py
api/routers/areas.py
api/routers/config.py
api/tests/app/test_area_occupancy_rules.py
libs/config_engine.py
libs/entities/occupancy_rule.py
libs/metrics/base.py
libs/metrics/in_out.py

Also add a small fix for In/Out with latest changes to entities classes

Merge endpoints for area and occupancy

---

libs/metrics/base.py
libs/metrics/face_mask_usage.py
libs/metrics/social_distancing.py

This PR adds a different way of aggregating face mask and social distancing metrics. Prior to this a single person (identified by track id) could be logged as wearing facemask as well as not wearing it. This case could be suitable for places where people spend a lot of time and might remove their mask.
The new mode will only ever add 1 to either N/A, Using Facemask or Not Using Facemask columns in the results. Weighted Max Voting is used to determine the label

Single metric aggregation

---

libs/cv_engine.py

Fix how we correct outlier FPS
